const genders = [
  'Action',
  'Indie',
  'Adventure',
  'RPG',
  'Strategy',
  'Shooter',
  'Casual',
  'Simulation',
  'Puzzle',
  'Arcade',
  'Platformer',
  'Racing',
  'Massively Multiplayer',
  'Sports',
  'Fighting',
  'Family',
  'Board Games',
  'Educational',
  'Card'
]
const plataform = [
  'PC',
  'PlayStation 5',
  'PlayStation 4',
  'Xbox One',
  'Xbox Series S/X',
  'Nintendo Switch',
  'iOS',
  'Android',
  'Nintendo 3DS',
  'Nintendo DS',
  'Nintendo DSi',
  'macOS',
  'Linux',
  'Xbox 360',
  'Xbox',
  'PlayStation 3',
  'PlayStation 2',
  'PlayStation',
  'PS Vita',
  'PSP',
  'Wii U',
  'Wii',
  'GameCube',
  'Nintendo 64',
  'Game Boy Advance',
  'Game Boy Color',
  'Game Boy',
  'SNES',
  'NES',
  'Classic Macintosh',
  'Apple II',
  'Commodore / Amiga',
  'Atari 7800',
  'Atari 5200',
  'Atari 2600',
  'Atari Flashback',
  'Atari 8-bit',
  'Atari ST',
  'Atari Lynx',
  'Atari XEGS',
  'Genesis',
  'SEGA Saturn',
  'SEGA CD',
  'SEGA 32X',
  'SEGA Master System',
  'Dreamcast',
  '3DO',
  'Jaguar',
  'Game Gear',
  'Neo Geo'
]

const tags = [
  'Singleplayer',
  'Steam Achievements',
  'Multiplayer',
  'Full controller support',
  'Atmospheric',
  'Steam Cloud',
  'steam-trading-cards',
  'Great Soundtrack',
  'RPG',
  'Co-op'
]

const stores = [
  'Steam',
  'PlayStation Store',
  'Xbox Store',
  'App Store',
  'GOG',
  'Nintendo Store',
  'Xbox 360 Store',
  'Google Play',
  'itch.io',
  'Epic Games'
]

export { genders, plataform, tags, stores }
